version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3  # Persist SQLite database
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/build:/frontend/build
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"