version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3  # Persist SQLite database
      - ./backend/images:/app/images  # Add this line to mount the images directory
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    volumes:
      - react_build:/frontend/build
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"

  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/frontend
      - ./backend/images:/var/www/images  # Mount the images directory for Nginx
    depends_on:
      - backend
      - frontend

volumes:
  react_build:

